export const ICONS = {
    logo: require('../assets/icons/logo-notext.png'),
    icon_donut: require('../assets/icons/icon-donut.png'),
    icon_invoice: require('../assets/icons/icon-invoice.png'),
    icon_location: require('../assets/icons/icon-location.png'),
    icon_noti: require('../assets/icons/icon-noti.png'),
    icon_feature1: require('../assets/icons/icon-feature1.png'),
    icon_feature2: require('../assets/icons/icon-feature2.png'),
    icon_feature3: require('../assets/icons/icon-feature3.png'),
    camera: require('../assets/icons/camera.png'),
    lightbulb: require('../assets/icons/lightbulb.png'),
    cart: require('../assets/icons/cart.png'),
    user: require('../assets/icons/user.png'),
    icon_homepage: require('../assets/icons/icon-homepage.png'),
    icon_order: require('../assets/icons/icon-order.png'),
    icon_cart: require('../assets/icons/icon-cart.png'),
    icon_heart: require('../assets/icons/icon-heart.png'),
    icon_setting: require('../assets/icons/icon-setting.png'),
    icon_logout: require('../assets/icons/icon-logout.png'),
    cart_2: require('../assets/icons/cart_2.png'),
    hearts: require('../assets/icons/hearts.png'),
    star: require('../assets/icons/star.png'),
    fill_heart: require('../assets/icons/fill-heart.png'),
    arrow_right: require('../assets/icons/arrowRight.png'),
    eye: require('../assets/icons/eye.png'),
    plus: require('../assets/icons/macOS_Maximize.png'),
    minus: require('../assets/icons/minus.png'),
    cart: require('../assets/icons/vector.png'),
    arrow_right: require('../assets/icons/arrow_right.png'),
    arrow_left: require('../assets/icons/arrow_left.png'),
    time_span: require('../assets/icons/time_span.png'),
};

